# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from weather_cpp/CurrentCondition.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CurrentCondition(genpy.Message):
  _md5sum = "54daa0cddcc3580a66a58d3b3c94c3d1"
  _type = "weather_cpp/CurrentCondition"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float32 tempMax
float32 tempHourly
float32 tempApparent
float32 rainfall
float32 icefall
float32 snowfall
float32 probTornado
float32 probHail
float32 probThunderWind
float32 probExTornado
float32 probExHail
float32 probExThunderWind

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','tempMax','tempHourly','tempApparent','rainfall','icefall','snowfall','probTornado','probHail','probThunderWind','probExTornado','probExHail','probExThunderWind']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,tempMax,tempHourly,tempApparent,rainfall,icefall,snowfall,probTornado,probHail,probThunderWind,probExTornado,probExHail,probExThunderWind

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CurrentCondition, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.tempMax is None:
        self.tempMax = 0.
      if self.tempHourly is None:
        self.tempHourly = 0.
      if self.tempApparent is None:
        self.tempApparent = 0.
      if self.rainfall is None:
        self.rainfall = 0.
      if self.icefall is None:
        self.icefall = 0.
      if self.snowfall is None:
        self.snowfall = 0.
      if self.probTornado is None:
        self.probTornado = 0.
      if self.probHail is None:
        self.probHail = 0.
      if self.probThunderWind is None:
        self.probThunderWind = 0.
      if self.probExTornado is None:
        self.probExTornado = 0.
      if self.probExHail is None:
        self.probExHail = 0.
      if self.probExThunderWind is None:
        self.probExThunderWind = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.tempMax = 0.
      self.tempHourly = 0.
      self.tempApparent = 0.
      self.rainfall = 0.
      self.icefall = 0.
      self.snowfall = 0.
      self.probTornado = 0.
      self.probHail = 0.
      self.probThunderWind = 0.
      self.probExTornado = 0.
      self.probExHail = 0.
      self.probExThunderWind = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12f.pack(_x.tempMax, _x.tempHourly, _x.tempApparent, _x.rainfall, _x.icefall, _x.snowfall, _x.probTornado, _x.probHail, _x.probThunderWind, _x.probExTornado, _x.probExHail, _x.probExThunderWind))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.tempMax, _x.tempHourly, _x.tempApparent, _x.rainfall, _x.icefall, _x.snowfall, _x.probTornado, _x.probHail, _x.probThunderWind, _x.probExTornado, _x.probExHail, _x.probExThunderWind,) = _struct_12f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12f.pack(_x.tempMax, _x.tempHourly, _x.tempApparent, _x.rainfall, _x.icefall, _x.snowfall, _x.probTornado, _x.probHail, _x.probThunderWind, _x.probExTornado, _x.probExHail, _x.probExThunderWind))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.tempMax, _x.tempHourly, _x.tempApparent, _x.rainfall, _x.icefall, _x.snowfall, _x.probTornado, _x.probHail, _x.probThunderWind, _x.probExTornado, _x.probExHail, _x.probExThunderWind,) = _struct_12f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_12f = struct.Struct("<12f")
