// Generated by gencpp from file weather_cpp/CurrentCondition.msg
// DO NOT EDIT!


#ifndef WEATHER_CPP_MESSAGE_CURRENTCONDITION_H
#define WEATHER_CPP_MESSAGE_CURRENTCONDITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace weather_cpp
{
template <class ContainerAllocator>
struct CurrentCondition_
{
  typedef CurrentCondition_<ContainerAllocator> Type;

  CurrentCondition_()
    : header()
    , temperature()
    , humidity()
    , windSpeed()
    , dewpoint()
    , visibility()
    , windchill()
    , lastUpdate()  {
    }
  CurrentCondition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temperature(_alloc)
    , humidity(_alloc)
    , windSpeed(_alloc)
    , dewpoint(_alloc)
    , visibility(_alloc)
    , windchill(_alloc)
    , lastUpdate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _temperature_type;
  _temperature_type temperature;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _humidity_type;
  _humidity_type humidity;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _windSpeed_type;
  _windSpeed_type windSpeed;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dewpoint_type;
  _dewpoint_type dewpoint;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _visibility_type;
  _visibility_type visibility;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _windchill_type;
  _windchill_type windchill;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lastUpdate_type;
  _lastUpdate_type lastUpdate;




  typedef boost::shared_ptr< ::weather_cpp::CurrentCondition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weather_cpp::CurrentCondition_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentCondition_

typedef ::weather_cpp::CurrentCondition_<std::allocator<void> > CurrentCondition;

typedef boost::shared_ptr< ::weather_cpp::CurrentCondition > CurrentConditionPtr;
typedef boost::shared_ptr< ::weather_cpp::CurrentCondition const> CurrentConditionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weather_cpp::CurrentCondition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weather_cpp::CurrentCondition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace weather_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'weather_cpp': ['/home/ros/EE5900_Repos/EE5900-Proj1-Group4/weather_cpp/catkin_ws/src/weather_cpp/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather_cpp::CurrentCondition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather_cpp::CurrentCondition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_cpp::CurrentCondition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26bdc8d77dad89eb3673a16e5de86c17";
  }

  static const char* value(const ::weather_cpp::CurrentCondition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26bdc8d77dad89ebULL;
  static const uint64_t static_value2 = 0x3673a16e5de86c17ULL;
};

template<class ContainerAllocator>
struct DataType< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weather_cpp/CurrentCondition";
  }

  static const char* value(const ::weather_cpp::CurrentCondition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string temperature\n\
string humidity\n\
string windSpeed\n\
string dewpoint\n\
string visibility\n\
string windchill\n\
string lastUpdate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::weather_cpp::CurrentCondition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temperature);
      stream.next(m.humidity);
      stream.next(m.windSpeed);
      stream.next(m.dewpoint);
      stream.next(m.visibility);
      stream.next(m.windchill);
      stream.next(m.lastUpdate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentCondition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weather_cpp::CurrentCondition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weather_cpp::CurrentCondition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temperature: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.humidity);
    s << indent << "windSpeed: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.windSpeed);
    s << indent << "dewpoint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dewpoint);
    s << indent << "visibility: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.visibility);
    s << indent << "windchill: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.windchill);
    s << indent << "lastUpdate: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lastUpdate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEATHER_CPP_MESSAGE_CURRENTCONDITION_H
